apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  #namespace: node-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
    protocol: TCP
    name: nginx
  selector:
    app: nginx
  sessionAffinity: None
status:
  loadBalancer: {}
