apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  #namespace: node-api
spec:
  selector:
    matchLabels:
      app: node-api
      release: canary
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: node-api
        release: canary
    spec:
      containers:
      - name: node-api
        image: moontea/node-api:1.0.0
        ports:
        - containerPort: 3000
