apiVersion: v1
kind: Service
metadata:
  name: node-api
  #namespace: node-api
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: node-api
  selector:
    app: node-api
  sessionAffinity: None
status:
  loadBalancer: {}
