apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  #namespace: node-api
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 1
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: moontea/node-api:1.0.0
        ports:
        - containerPort: 3000
